# Generated by Django 2.2.6 on 2019-10-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ref_url', models.CharField(max_length=200)),
                ('img_name', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ref_url', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('review_time', models.CharField(max_length=200)),
                ('approval_percent', models.CharField(max_length=200)),
                ('addition', models.CharField(max_length=200)),
                ('raiting', models.IntegerField(default=5)),
                ('position', models.IntegerField(default=0)),
                ('reviews_count', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=4000)),
                ('company_name', models.CharField(choices=[('DINERO', 'Dinero'), ('MONEYVEO', 'Moneyveo'), ('CREDIT7', 'Credit7'), ('MYCREDIT', 'MyCredit'), ('MILOAN', 'Miloan'), ('KREDIT-PLUS', 'Kredit-Plus'), ('ALEXCREDIT', 'AlexCredit'), ('BYSTROZAJM', 'BystroZajm')], default='-', max_length=30)),
                ('company_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=200)),
            ],
        ),
    ]
