# Generated by Django 2.2.6 on 2019-11-18 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ref_url', models.CharField(max_length=200)),
                ('img_name', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Compony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ref_url', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('review_time', models.CharField(max_length=200)),
                ('approval_percent', models.CharField(max_length=200)),
                ('addition', models.CharField(max_length=200)),
                ('raiting', models.IntegerField(default=5)),
                ('position', models.IntegerField(default=0)),
                ('reviews_count', models.IntegerField(default=50)),
                ('main_photo', models.ImageField(default='', upload_to='Construction/static/roof/img', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=4000)),
                ('company_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('approved', models.BooleanField(default=False)),
                ('company_nama', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Compony')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('position', models.CharField(choices=[('alert_left', 'Left'), ('alert_right', 'Right')], default='', max_length=30)),
                ('company_nama', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Compony')),
            ],
        ),
    ]
