# Generated by Django 2.2.6 on 2019-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191018_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='company_name',
            field=models.CharField(choices=[('DINERO', 'Dinero'), ('MONEYVEO', 'Moneyveo'), ('CREDIT7', 'Credit7'), ('MYCREDIT', 'MyCredit'), ('MILOAN', 'Miloan'), ('KREDIT-PLUS', 'Kredit-Plus'), ('ALEXCREDIT', 'AlexCredit'), ('BYSTROZAJM', 'BystroZajm')], default='-', max_length=30),
        ),
    ]
