# Generated by Django 2.2.7 on 2019-12-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191118_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compony',
            name='main_photo',
            field=models.ImageField(default='', upload_to='compony/img', verbose_name='Фото'),
        ),
    ]
