# Generated by Django 2.2.7 on 2019-12-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='company_nama',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='compony',
            name='ref_url',
        ),
    ]
