# Generated by Django 2.2.6 on 2019-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191018_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='company_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
