# Generated by Django 2.2.7 on 2019-12-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redir', '0002_auto_20191228_1317'),
        ('post', '0005_auto_20191228_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='compony',
            name='redirect_ref_url',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='redir.Redirect'),
        ),
    ]
