# Generated by Django 2.2.6 on 2019-10-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20191018_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
