# Generated by Django 2.2.6 on 2019-10-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20191018_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
