# Generated by Django 2.2.6 on 2019-10-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20191018_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
