# Generated by Django 2.2.6 on 2019-10-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20191018_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('alert_left', 'Left'), ('alert_right', 'Right')], default='-', max_length=30)),
            ],
        ),
    ]
