# Generated by Django 2.2.6 on 2019-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='company_name',
            field=models.CharField(choices=[('// Dinero//', 'Dinero'), ('https://www.google.com/', 'Moneyveo'), ('https://targetme.go2cloud.org/SHk', 'Credit7'), ('https://www.google.com/', 'MyCredit'), ('https://www.google.com/', 'Miloan'), ('https://www.google.com/', 'Kredit-Plus'), ('https://www.google.com/', 'AlexCredit'), ('https://www.google.com/', 'BystroZajm')], default='-', max_length=30),
        ),
    ]
