# Generated by Django 2.2.6 on 2019-10-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20191024_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='company_name',
            field=models.CharField(choices=[('//Dinero//', 'Dinero'), ('https://www.google.com/6', 'Moneyveo'), ('https://targetme.go2cloud.org/SHk', 'Credit7'), ('https://www.google.com/5', 'MyCredit'), ('https://www.google.com/4', 'Miloan'), ('https://www.google.com/3', 'Kredit-Plus'), ('https://www.google.com/2', 'AlexCredit'), ('https://www.google.com/1', 'BystroZajm')], default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='company_name',
            field=models.CharField(choices=[('//Dinero//', 'Dinero'), ('https://www.google.com/6', 'Moneyveo'), ('https://targetme.go2cloud.org/SHk', 'Credit7'), ('https://www.google.com/5', 'MyCredit'), ('https://www.google.com/4', 'Miloan'), ('https://www.google.com/3', 'Kredit-Plus'), ('https://www.google.com/2', 'AlexCredit'), ('https://www.google.com/1', 'BystroZajm')], default='-', max_length=255),
        ),
    ]
