# Generated by Django 2.2.7 on 2019-12-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='ref_url',
            field=models.CharField(max_length=300),
        ),
    ]
